
import BabyShowerDecoration from "../assets/images/BabyShowerDecoration.jpg"; // Importing images
import BirthdayDecoration from "../assets/images/BirthdayDecoration.jpg";
import WeddingDecoration from "../assets/images/WeddingDecoration.jpg";
import GaneshaDecoration from "../assets/images/GaneshaDecoration.jpg";
import AnniversaryDecoration from "../assets/images/AnniversaryDecoration.jpg";

export const categories = [
  {
    name: 'Birthday',
    image: BirthdayDecoration,
    description: 'Celebrate birthdays with fun decorations, themes, and party vibes that create lasting memories.',
    items: [
      {
        id: 1,  // Unique ID
        title: 'Birthday Balloons',
        image: BabyShowerDecoration,
        price: 4000,
        description: 'Bright and colorful balloons to brighten up the party atmosphere.',
        itemsUsed: ['Helium', 'String', 'Weights'],
      },
      {
        id: 2,  // Unique ID
        title: 'Birthday Cake Setup',
        image: BirthdayDecoration,
        price: 12000,
        description: 'A beautifully arranged cake with candles and decorative elements.',
        itemsUsed: ['Cake', 'Candles', 'Tablecloth', 'Cake Stand'],
      },
      {
        id: 3,  // Unique ID
        title: 'Party Lights',
        image: WeddingDecoration,
        price: 8000,
        description: 'String lights to create a magical ambiance.',
        itemsUsed: ['LED Lights', 'Extension Cords', 'Hooks'],
      },
      {
        id: 4,  // Unique ID
        title: 'Birthday Hat',
        image: GaneshaDecoration,
        price: 2000,
        description: 'Fun party hats for all guests to wear during the celebration.',
        itemsUsed: ['Paper', 'Elastic Bands', 'Glue'],
      },
      {
        id: 5,  // Unique ID
        title: 'Birthday Banner',
        image: AnniversaryDecoration,
        price: 1500,
        description: 'A festive banner to announce the birthday celebration.',
        itemsUsed: ['Cardstock', 'Rope', 'Markers'],
      },
    ],
  },
  {
    name: 'Baby Shower',
    image: BabyShowerDecoration,
    description: 'Cherish the joy of a new beginning with beautiful baby shower decorations and moments to treasure forever.',
    items: [
      {
        id: 6,  // Unique ID
        title: 'Baby Shower Banners',
        image: BabyShowerDecoration,
        price: 5000,
        description: 'Lovely banners to celebrate the upcoming arrival.',
        itemsUsed: ['Fabric', 'Rope', 'Stickers'],
      },
      {
        id: 7,  // Unique ID
        title: 'Gender Reveal Setup',
        image: BirthdayDecoration,
        price: 15000,
        description: 'Complete setup for the gender reveal moment.',
        itemsUsed: ['Confetti', 'Balloon Box', 'Banners'],
      },
      {
        id: 8,  // Unique ID
        title: 'Flower Decorations',
        image: WeddingDecoration,
        price: 10000,
        description: 'Beautiful floral arrangements to enhance the venue.',
        itemsUsed: ['Fresh Flowers', 'Vases', 'Ribbon'],
      },
      {
        id: 9,  // Unique ID
        title: 'Baby Shower Favors',
        image: GaneshaDecoration,
        price: 3500,
        description: 'Gifts for guests to take home as a memento.',
        itemsUsed: ['Small Boxes', 'Candy', 'Labels'],
      },
      {
        id: 10,  // Unique ID
        title: 'Diaper Cake',
        image: AnniversaryDecoration,
        price: 6000,
        description: 'A creative arrangement of diapers for the new parents.',
        itemsUsed: ['Diapers', 'Ribbons', 'Decorative Accents'],
      },
    ],
  },
  {
    name: 'Ganapati Decoration',
    image: GaneshaDecoration,
    description: 'Traditional yet modern Ganapati decorations that bring vibrancy and festivity to your celebrations.',
    items: [
      {
        id: 11,  // Unique ID
        title: 'Ganapati Mandap',
        image: GaneshaDecoration,
        price: 40000,
        description: 'A beautifully decorated area for worshipping Ganapati.',
        itemsUsed: ['Fabric', 'Lights', 'Flowers'],
      },
      {
        id: 12,  // Unique ID
        title: 'Flower Garland',
        image: BabyShowerDecoration,
        price: 6000,
        description: 'Colorful flower garlands to adorn the idol.',
        itemsUsed: ['Fresh Flowers', 'Thread'],
      },
      {
        id: 13,  // Unique ID
        title: 'Lighting Setup',
        image: BirthdayDecoration,
        price: 25000,
        description: 'Lighting setup to enhance the festive atmosphere.',
        itemsUsed: ['LED Lights', 'Cables', 'Controllers'],
      },
      {
        id: 14,  // Unique ID
        title: 'Puja Items',
        image: WeddingDecoration,
        price: 12000,
        description: 'Essential items required for the pooja rituals.',
        itemsUsed: ['Incense Sticks', 'Ritual Plates', 'Candles'],
      },
      {
        id: 15,  // Unique ID
        title: 'Statue of Ganapati',
        image: AnniversaryDecoration,
        price: 15000,
        description: 'Beautiful idol of Ganapati for worship.',
        itemsUsed: ['Clay', 'Paint', 'Decorative Items'],
      },
    ],
  },
  {
    name: 'Anniversary',
    image: WeddingDecoration,
    description: 'Create your dream wedding with elegant and luxurious decorations that turn your special day into magic.',
    items: [
      {
        id: 16,  // Unique ID
        title: 'Wedding Arch',
        image: WeddingDecoration,
        price: 80000,
        description: 'A stunning arch to frame the wedding ceremony.',
        itemsUsed: ['Fabric', 'Flowers', 'Wood'],
      },
      {
        id: 17,  // Unique ID
        title: 'Flower Arrangements',
        image: BabyShowerDecoration,
        price: 60000,
        description: 'Elegant floral arrangements for tables and venues.',
        itemsUsed: ['Fresh Flowers', 'Vases', 'Filler Greens'],
      },
      {
        id: 18,  // Unique ID
        title: 'Table Decor',
        image: BirthdayDecoration,
        price: 30000,
        description: 'Complete table setup with decor elements.',
        itemsUsed: ['Tablecloths', 'Centerpieces', 'Cutlery'],
      },
      {
        id: 19,  // Unique ID
        title: 'Chair Covers',
        image: AnniversaryDecoration,
        price: 10000,
        description: 'Stylish covers to enhance the look of chairs.',
        itemsUsed: ['Fabric', 'Sashes', 'Ribbons'],
      },
      {
        id: 20,  // Unique ID
        title: 'Photo Booth Setup',
        image: GaneshaDecoration,
        price: 20000,
        description: 'A fun photo booth area for guests to capture memories.',
        itemsUsed: ['Backdrop', 'Props', 'Camera'],
      },
    ],
  },
  // {
  //   name: 'Anniversary Celebration',
  //   image: AnniversaryDecoration,
  //   description: 'Celebrate love and togetherness with anniversary decorations that make every milestone unforgettable.',
  //   items: [
  //     {
  //       id: 21,  // Unique ID
  //       title: 'Anniversary Balloons',
  //       image: AnniversaryDecoration,
  //       price: 5500,
  //       description: 'Special balloons to mark the anniversary celebration.',
  //       itemsUsed: ['Helium', 'String', 'Weights'],
  //     },
  //     {
  //       id: 22,  // Unique ID
  //       title: 'Romantic Lighting',
  //       image: BirthdayDecoration,
  //       price: 12000,
  //       description: 'Soft lighting to create a romantic ambiance.',
  //       itemsUsed: ['Fairy Lights', 'Candles', 'Lanterns'],
  //     },
  //     {
  //       id: 23,  // Unique ID
  //       title: 'Floral Setup',
  //       image: BabyShowerDecoration,
  //       price: 15000,
  //       description: 'A beautiful floral arrangement to enhance the venue.',
  //       itemsUsed: ['Fresh Flowers', 'Vases', 'Greenery'],
  //     },
  //     {
  //       id: 24,  // Unique ID
  //       title: 'Love Letters Decor',
  //       image: BirthdayDecoration,
  //       price: 7000,
  //       description: 'Decorative letters spelling out "LOVE".',
  //       itemsUsed: ['Wood', 'Paint', 'Decorative Accents'],
  //     },
  //     {
  //       id: 25,  // Unique ID
  //       title: 'Cake Table Decor',
  //       image: GaneshaDecoration,
  //       price: 8000,
  //       description: 'Beautiful decor for the cake display table.',
  //       itemsUsed: ['Tablecloth', 'Stand', 'Flowers'],
  //     },
  //   ],
  // },
];

export const Products=[
    {
      productId: 1,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 2,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 3,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 4,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 5,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 6,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 7,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 8,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 9,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 10,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 11,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 12,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 13,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 14,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 15,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 16,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 17,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 18,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 19,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 20,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 21,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 22,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 23,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 24,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 25,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 26,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 27,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 28,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 29,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 30,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 31,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 32,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 33,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 34,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 35,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 36,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 37,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 38,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 39,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 40,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 41,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 42,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 43,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 44,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 45,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 46,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 47,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 48,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 49,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 50,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 51,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 52,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 53,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 54,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 55,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 56,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 57,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 58,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 59,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 60,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 61,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 62,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 63,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 64,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 65,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 66,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 67,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 68,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 69,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 70,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 71,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 72,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 73,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 74,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 75,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 76,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 77,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 78,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 79,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 80,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 81,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 82,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 83,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 84,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 85,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 86,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 87,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 88,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 89,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 90,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 91,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 92,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 93,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 94,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA433.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 95,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA587.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
    {
      productId: 96,
      productName: "Gold and Black Arch Birthday Decor",
      image: "https://img.ebonow.com/Products/CLA575.webp",
      originalPrice: 4284,
      discountPrice: 2159,
      discountPercentage: 50,
      categoryName: "Birthday",
    },
    {
      productId: 97,
      productName: "Unicorn Theme Birthday Party Kit",
      image: "https://img.ebonow.com/Products/CLA595.webp",
      originalPrice: 3499,
      discountPrice: 2799,
      discountPercentage: 20,
      categoryName: "Birthday",
    },
    {
      productId: 98,
      productName: "Blue Baby Shower Balloon Set",
      image: "https://img.ebonow.com/Products/CLA571.webp",
      originalPrice: 3299,
      discountPrice: 2499,
      discountPercentage: 24,
      categoryName: "Baby Shower",
    },
    {
      productId: 99,
      productName: "Romantic Anniversary Candlelight Setup",
      image: "https://img.ebonow.com/Products/CLA262.webp",
      originalPrice: 5999,
      discountPrice: 4999,
      discountPercentage: 17,
      categoryName: "Anniversary",
    },
    {
      productId: 100,
      productName: "Ganapati Pandal Decoration Kit",
      image: "https://img.ebonow.com/Products/CLA612.webp",
      originalPrice: 5599,
      discountPrice: 3999,
      discountPercentage: 29,
      categoryName: "Ganapati Decoration",
    },
];
  







// import BabyShowerDecoration from "../assets/images/BabyShowerDecoration.jpg"; // Importing images
// import BirthdayDecoration from "../assets/images/BirthdayDecoration.jpg";
// import WeddingDecoration from "../assets/images/WeddingDecoration.jpg";
// import GaneshaDecoration from "../assets/images/GaneshaDecoration.jpg";
// import AnniversaryDecoration from "../assets/images/AnniversaryDecoration.jpg";


// export const categories = [
//     {
//       name: 'Birthday',
//       image: BirthdayDecoration,
//       description: 'Celebrate birthdays with fun decorations, themes, and party vibes that create lasting memories.',
//       items: [
//         {
//           title: 'Birthday Balloons',
//           // image: BabyShowerDecoration,
//           image: BabyShowerDecoration,
//           price: 4000,
//           description: 'Bright and colorful balloons to brighten up the party atmosphere.',
//           itemsUsed: ['Helium', 'String', 'Weights']
//         },
//         {
//           title: 'Birthday Cake Setup',
//           image: BirthdayDecoration,
//           price: 12000,
//           description: 'A beautifully arranged cake with candles and decorative elements.',
//           itemsUsed: ['Cake', 'Candles', 'Tablecloth', 'Cake Stand']
//         },
//         {
//           title: 'Party Lights',
//           image: WeddingDecoration,
//           price: 8000,
//           description: 'String lights to create a magical ambiance.',
//           itemsUsed: ['LED Lights', 'Extension Cords', 'Hooks']
//         },
//         {
//           title: 'Birthday Hat',
//           image: GaneshaDecoration,
//           price: 2000,
//           description: 'Fun party hats for all guests to wear during the celebration.',
//           itemsUsed: ['Paper', 'Elastic Bands', 'Glue']
//         },
//         {
//           title: 'Birthday Banner',
//           image: AnniversaryDecoration,
//           price: 1500,
//           description: 'A festive banner to announce the birthday celebration.',
//           itemsUsed: ['Cardstock', 'Rope', 'Markers']
//         },
//       ],
//     },
//     {
//       name: 'Baby Shower',
//       image: BabyShowerDecoration,
//       description: 'Cherish the joy of a new beginning with beautiful baby shower decorations and moments to treasure forever.',
//       items: [
//         {
//           title: 'Baby Shower Banners',
//           image: BabyShowerDecoration,
//           price: 5000,
//           description: 'Lovely banners to celebrate the upcoming arrival.',
//           itemsUsed: ['Fabric', 'Rope', 'Stickers']
//         },
//         {
//           title: 'Gender Reveal Setup',
//           image: BirthdayDecoration,
//           price: 15000,
//           description: 'Complete setup for the gender reveal moment.',
//           itemsUsed: ['Confetti', 'Balloon Box', 'Banners']
//         },
//         {
//           title: 'Flower Decorations',
//           image: WeddingDecoration,
//           price: 10000,
//           description: 'Beautiful floral arrangements to enhance the venue.',
//           itemsUsed: ['Fresh Flowers', 'Vases', 'Ribbon']
//         },
//         {
//           title: 'Baby Shower Favors',
//           image: GaneshaDecoration,
//           price: 3500,
//           description: 'Gifts for guests to take home as a memento.',
//           itemsUsed: ['Small Boxes', 'Candy', 'Labels']
//         },
//         {
//           title: 'Diaper Cake',
//           image: AnniversaryDecoration,
//           price: 6000,
//           description: 'A creative arrangement of diapers for the new parents.',
//           itemsUsed: ['Diapers', 'Ribbons', 'Decorative Accents']
//         },
//       ],
//     },
//     {
//       name: 'Ganapati Decoration',
//       image: GaneshaDecoration,
//       description: 'Traditional yet modern Ganapati decorations that bring vibrancy and festivity to your celebrations.',
//       items: [
//         {
//           title: 'Ganapati Mandap',
//           image: GaneshaDecoration,
//           price: 40000,
//           description: 'A beautifully decorated area for worshipping Ganapati.',
//           itemsUsed: ['Fabric', 'Lights', 'Flowers']
//         },
//         {
//           title: 'Flower Garland',
//           image: BabyShowerDecoration,
//           price: 6000,
//           description: 'Colorful flower garlands to adorn the idol.',
//           itemsUsed: ['Fresh Flowers', 'Thread']
//         },
//         {
//           title: 'Lighting Setup',
//           image: BirthdayDecoration,
//           price: 25000,
//           description: 'Lighting setup to enhance the festive atmosphere.',
//           itemsUsed: ['LED Lights', 'Cables', 'Controllers']
//         },
//         {
//           title: 'Puja Items',
//           image: WeddingDecoration,
//           price: 12000,
//           description: 'Essential items required for the pooja rituals.',
//           itemsUsed: ['Incense Sticks', 'Ritual Plates', 'Candles']
//         },
//         {
//           title: 'Statue of Ganapati',
//           image: AnniversaryDecoration,
//           price: 15000,
//           description: 'Beautiful idol of Ganapati for worship.',
//           itemsUsed: ['Clay', 'Paint', 'Decorative Items']
//         },
//       ],
//     },
//     {
//       name: 'Wedding Decoration',
//       image: WeddingDecoration,
//       description: 'Create your dream wedding with elegant and luxurious decorations that turn your special day into magic.',
//       items: [
//         {
//           title: 'Wedding Arch',
//           image: WeddingDecoration,
//           price: 80000,
//           description: 'A stunning arch to frame the wedding ceremony.',
//           itemsUsed: ['Fabric', 'Flowers', 'Wood']
//         },
//         {
//           title: 'Flower Arrangements',
//           image: BabyShowerDecoration,
//           price: 60000,
//           description: 'Elegant floral arrangements for tables and venues.',
//           itemsUsed: ['Fresh Flowers', 'Vases', 'Filler Greens']
//         },
//         {
//           title: 'Table Decor',
//           image: BirthdayDecoration,
//           price: 30000,
//           description: 'Complete table setup with decor elements.',
//           itemsUsed: ['Tablecloths', 'Centerpieces', 'Cutlery']
//         },
//         {
//           title: 'Chair Covers',
//           image: AnniversaryDecoration,
//           price: 10000,
//           description: 'Stylish covers to enhance the look of chairs.',
//           itemsUsed: ['Fabric', 'Sashes', 'Ribbons']
//         },
//         {
//           title: 'Photo Booth Setup',
//           image: GaneshaDecoration,
//           price: 20000,
//           description: 'A fun photo booth area for guests to capture memories.',
//           itemsUsed: ['Backdrop', 'Props', 'Camera']
//         },
//       ],
//     },
//     {
//       name: 'Anniversary Celebration',
//       image: AnniversaryDecoration,
//       description: 'Celebrate love and togetherness with anniversary decorations that make every milestone unforgettable.',
//       items: [
//         {
//           title: 'Anniversary Balloons',
//           image: AnniversaryDecoration,
//           price: 5500,
//           description: 'Special balloons to mark the anniversary celebration.',
//           itemsUsed: ['Helium', 'String', 'Weights']
//         },
//         {
//           title: 'Romantic Lighting',
//           image: BirthdayDecoration,
//           price: 12000,
//           description: 'Soft lighting to create a romantic ambiance.',
//           itemsUsed: ['Fairy Lights', 'Candles', 'Lanterns']
//         },
//         {
//           title: 'Floral Setup',
//           image: BabyShowerDecoration,
//           price: 15000,
//           description: 'A beautiful floral arrangement to enhance the venue.',
//           itemsUsed: ['Fresh Flowers', 'Vases', 'Greenery']
//         },
//         {
//           title: 'Love Letters Decor',
//           image: BirthdayDecoration,
//           price: 7000,
//           description: 'Decorative letters spelling out "LOVE".',
//           itemsUsed: ['Wood', 'Paint', 'Decorative Accents']
//         },
//         {
//           title: 'Cake Table Decor',
//           image: GaneshaDecoration,
//           price: 8000,
//           description: 'Beautiful decor for the cake display table.',
//           itemsUsed: ['Tablecloth', 'Stand', 'Flowers']
//         },
//       ],
//     },
//   ];
